### ISSUE TITLE
get_augmented_network_input function is missing

### ISSUE THREAD

**Issue by kvr777** [vikasverma1077/GraphMix#4]
Hi, thank you for the great repo. 
I found out that inside of GNN class, the function forward_mix is not working because function get_augmented_network_input is missing. 
Did you just forget to delete forward_mix function (as I understood you don't use it in this example) or the function get_augmented_network_input should be added in the code?

**Comment by vikasverma1077** [comment]
Hello, thanks for your interest. That function is not in use anymore.
